name: Inject Token

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      
      - name: Setup Jekyll
        uses: actions/jekyll-build-pages@v1
        
      - name: Inject token
        run: |
          sed -i "s/github_pat_YOUR_TOKEN/${{ secrets.METRICS_TOKEN }}/g" _layouts/blog.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.METRICS_TOKEN }}
          publish_dir: ./_site
          force_orphan: true